---

- block:
  - name: "Install puppet agent"
    package:
      name: puppet
      state: present
  - service:
      name: puppet
      enabled: yes
      state: started

- name: "Modify puppet.conf"
  template:
    src: puppet.conf.j2
    dest: /etc/puppet/puppet.conf
  no_log: yes
  with_together:
    - "{{ mastername }}"
    - "{{ inventory_hostname }}"

- name: "Enable puppet agent"
  shell: /usr/bin/puppet agent --enable --verbose

- name: "Start puppet agent"
  # https://docs.puppet.com/puppet/3/man/agent.html
  # With --detailed-exitcodes, an exit code of '2' means there were changes.
  shell: /usr/bin/puppet agent --test --verbose --detailed-exitcodes
  register: puppet_agent
  changed_when: puppet_agent.rc == 2
  failed_when: puppet_agent.rc != 2 and puppet_agent.rc != 0
