---

- name: Install ntp pacakge
  package:
    name: ntp
    state: present
  register: ntp_install_result

- name: Force an immediate update on fresh installation
  block:
  - name: Stop ntp service
    service:
      name: ntp
      state: stopped
  - name: Update time
    command: ntpdate pool.ntp.org
  when: ntp_install_result.changed

- name: Start ntp service
  service:
    name: ntp
    state: started

- name: Modify /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1.*$"
    line: "127.0.0.1 {{ inventory_hostname }} localhost"

- name: Modify hostname
  hostname:
    name: "{{ inventory_hostname }}"
